Repository AY2021S2-CS2103-T16-2/tp, pull requests merged in 2021-03, with the labels that each got.

#27 Readme change status
  README.md
Labels: type.Bug, type.Task

#45 Add meetings dashboard
  src/main/java/seedu/address/model/meeting/DateTime.java
  src/main/java/seedu/address/model/meeting/Description.java
  src/main/java/seedu/address/model/meeting/Meeting.java
  src/main/java/seedu/address/model/meeting/Priority.java
  src/main/java/seedu/address/model/meeting/UniqueMeetingList.java
  src/main/java/seedu/address/model/meeting/exceptions/MeetingNotFoundException.java
  src/main/java/seedu/address/ui/MainWindow.java
  src/main/java/seedu/address/ui/MeetingCard.java
  src/main/java/seedu/address/ui/MeetingDashboard.java
  src/main/java/seedu/address/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/MeetingCard.fxml
  src/main/resources/view/MeetingDashboard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: priority.High

#56 Change address, email, and phone to optional during add by using plac…
  src/main/java/seedu/address/logic/parser/persons/AddPersonCommandParser.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/parser/persons/AddPersonCommandParserTest.java
Labels: priority.Medium

#77 Add reminders, still need to add to UI
  src/main/java/seedu/address/logic/commands/reminders/RefreshRemindersCommand.java
  src/main/java/seedu/address/logic/parser/MeetBuddyParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/reminder/ReadOnlyReminderBook.java
  src/main/java/seedu/address/model/reminder/Reminder.java
  src/main/java/seedu/address/model/reminder/ReminderBook.java
  src/main/java/seedu/address/model/reminder/UniqueReminderList.java
  src/test/java/seedu/address/logic/commands/meetings/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/persons/AddPersonCommandTest.java
  src/test/java/seedu/address/model/reminder/ReminderTest.java
Labels: priority.Medium

#86 DG: Add a small section on the sorting features
  docs/DeveloperGuide.md
Labels: priority.High

#85 Sort people meeting
  src/main/java/seedu/address/logic/commands/meetings/SortMeetingCommand.java
  src/main/java/seedu/address/logic/commands/meetings/UnsortMeetingCommand.java
  src/main/java/seedu/address/logic/commands/persons/FindGroupCommand.java
  src/main/java/seedu/address/logic/commands/persons/SortPersonCommand.java
  src/main/java/seedu/address/logic/commands/persons/UnsortPersonCommand.java
  src/main/java/seedu/address/logic/parser/CliSyntax.java
  src/main/java/seedu/address/logic/parser/MeetBuddyParser.java
  src/main/java/seedu/address/logic/parser/meetings/SortMeetingCommandParser.java
  src/main/java/seedu/address/logic/parser/persons/SortPersonCommandParser.java
  src/main/java/seedu/address/model/Model.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/meeting/MeetingSortDirection.java
  src/main/java/seedu/address/model/meeting/MeetingSortOption.java
  src/main/java/seedu/address/model/person/Address.java
  src/main/java/seedu/address/model/person/Email.java
  src/main/java/seedu/address/model/person/PersonSortDirection.java
  src/main/java/seedu/address/model/person/PersonSortOption.java
  src/main/java/seedu/address/model/person/Phone.java
  src/test/java/seedu/address/logic/commands/meetings/AddMeetingCommandTest.java
  src/test/java/seedu/address/logic/commands/meetings/AddMeetingCommandWithConnectionTest.java
  src/test/java/seedu/address/logic/commands/persons/AddPersonCommandTest.java
Labels: priority.Medium
